spring.application.name=helmet-backend
spring.datasource.url=jdbc:mysql://server1.dnspark.in:3306/uvmtgikg_helmet?serverTimezone=UTC
spring.datasource.username=uvmtgikg_helm
spring.datasource.password=HelmetUser123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
